import nodemailer from "nodemailer";
import PDFDocument from "pdfkit";

export const toEmail = process.env.CONTACT_TO_EMAIL || "infobramcollp@gmail.com";

export function clean(value) {
  return String(value || "").trim();
}

export function escapeHtml(value) {
  return clean(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export function getTransport() {
  const host = process.env.SMTP_HOST;
  const port = Number(process.env.SMTP_PORT || 587);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!host || !user || !pass) {
    return null;
  }

  return nodemailer.createTransport({
    host,
    port,
    secure: process.env.SMTP_SECURE === "true" || port === 465,
    auth: {
      user,
      pass,
    },
  });
}

export function missingEmailConfigResponse() {
  return Response.json(
    {
      error:
        "Email service is not configured. Add RESEND_API_KEY and CONTACT_FROM_EMAIL, or SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, and CONTACT_FROM_EMAIL in .env.local.",
    },
    { status: 503 },
  );
}

async function sendWithResend({ subject, replyTo, title, sections, filename, pdf }) {
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey) {
    return false;
  }

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: process.env.CONTACT_FROM_EMAIL || "BRAM Website <no-reply@bramcollp.com>",
      to: [toEmail],
      reply_to: replyTo,
      subject,
      text: getText({ title, sections }),
      html: getHtml({ title, sections }),
      attachments: [
        {
          filename,
          content: pdf.toString("base64"),
        },
      ],
    }),
  });

  if (!response.ok) {
    let errorMessage = "Resend could not send the email.";

    try {
      const result = await response.json();
      errorMessage = result.message || result.error || errorMessage;
    } catch {
      errorMessage = await response.text();
    }

    throw new Error(errorMessage);
  }

  return true;
}

export function getPdfBuffer({ title, sections }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 42, size: "A4" });
    const chunks = [];
    const page = {
      width: doc.page.width,
      height: doc.page.height,
      margin: 42,
    };
    const colors = {
      ink: "#17201d",
      gold: "#c7a15a",
      goldDark: "#8a6b2f",
      paper: "#f7f5ef",
      muted: "#5b665f",
      line: "#ddd3c0",
      white: "#ffffff",
    };
    const contentWidth = page.width - page.margin * 2;

    function drawPageBase() {
      doc.rect(0, 0, page.width, page.height).fill(colors.paper);
      doc.rect(0, 0, page.width, 116).fill(colors.ink);
      doc.rect(page.margin, 34, 42, 42).fill(colors.gold);

      doc
        .fillColor(colors.ink)
        .fontSize(18)
        .text("B", page.margin, 45, { width: 42, align: "center" });

      doc
        .fillColor(colors.white)
        .fontSize(21)
        .text("BRAM & Co. LLP", page.margin + 58, 34)
        .fontSize(9)
        .fillColor("#d8d2c5")
        .text("CHARTERED ACCOUNTANTS | COST ACCOUNTANTS", page.margin + 58, 61, {
          characterSpacing: 1.2,
        })
        .fontSize(9)
        .fillColor("#f1d79d")
        .text("Client enquiry dossier", page.margin + 58, 84);

      doc
        .fillColor("#d8d2c5")
        .fontSize(8)
        .text("Generated by BRAM website", page.width - page.margin - 150, 36, {
          width: 150,
          align: "right",
        })
        .fillColor(colors.white)
        .fontSize(8)
        .text(new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }), page.width - page.margin - 150, 51, {
          width: 150,
          align: "right",
        });
    }

    function ensureSpace(height) {
      if (doc.y + height < page.height - 64) return;
      doc.addPage();
      drawPageBase();
      doc.y = 144;
    }

    function drawFooter() {
      const y = page.height - 42;

      doc
        .moveTo(page.margin, y - 10)
        .lineTo(page.width - page.margin, y - 10)
        .lineWidth(0.6)
        .strokeColor(colors.line)
        .stroke();

      doc
        .fillColor(colors.muted)
        .fontSize(8)
        .text("BRAM & Co. LLP | infobramcollp@gmail.com | www.bramcollp.com", page.margin, y, {
          width: contentWidth,
          align: "center",
        });
    }

    function drawField(label, value) {
      const cleanValue = clean(value) || "Not entered";
      const labelWidth = 150;
      const valueWidth = contentWidth - labelWidth - 28;
      const valueHeight = doc.heightOfString(cleanValue, { width: valueWidth });
      const rowHeight = Math.max(28, valueHeight + 14);

      ensureSpace(rowHeight + 4);

      const y = doc.y;

      doc
        .roundedRect(page.margin, y, contentWidth, rowHeight, 4)
        .fillAndStroke(colors.white, colors.line);

      doc
        .fillColor(colors.goldDark)
        .fontSize(8)
        .text(label.toUpperCase(), page.margin + 12, y + 10, {
          width: labelWidth,
          characterSpacing: 0.5,
        });

      doc
        .fillColor(colors.ink)
        .fontSize(10)
        .text(cleanValue, page.margin + labelWidth + 18, y + 9, {
          width: valueWidth,
          lineGap: 2,
        });

      doc.y = y + rowHeight + 6;
    }

    drawPageBase();

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc
      .y = 144;

    doc
      .fillColor(colors.goldDark)
      .fontSize(9)
      .text("ENQUIRY SUMMARY", page.margin, doc.y, {
        characterSpacing: 1.4,
      })
      .moveDown(0.5)
      .fillColor(colors.ink)
      .fontSize(22)
      .text(title, {
        width: contentWidth,
      });

    doc
      .moveDown(0.5)
      .fillColor(colors.muted)
      .fontSize(10)
      .text("The following information was submitted through the BRAM website and is formatted for internal review and follow-up.", {
        width: contentWidth,
        lineGap: 2,
      })
      .moveDown(1);

    sections.forEach((section) => {
      ensureSpace(58);

      const sectionY = doc.y;

      doc
        .roundedRect(page.margin, sectionY, contentWidth, 34, 4)
        .fill(colors.ink);

      doc
        .fillColor(colors.gold)
        .fontSize(12)
        .text(section.heading, page.margin + 14, sectionY + 10, {
          width: contentWidth - 28,
        });

      doc.y = sectionY + 43;

      section.rows.forEach(([label, value]) => {
        drawField(label, value);
      });

      doc.moveDown(0.4);
    });

    drawFooter();
    doc.end();
  });
}

export function getHtml({ title, sections }) {
  const body = sections
    .map(
      (section) => `
        <h3 style="margin:24px 0 8px;color:#8a6b2f">${escapeHtml(section.heading)}</h3>
        ${section.rows
          .map(
            ([label, value]) => `
              <p style="margin:6px 0"><strong>${escapeHtml(label)}:</strong> ${escapeHtml(value || "Not entered")}</p>
            `,
          )
          .join("")}
      `,
    )
    .join("");

  return `
    <div style="font-family:Arial,Helvetica,sans-serif;color:#17201d;line-height:1.6">
      <h2 style="margin:0 0 12px">${escapeHtml(title)}</h2>
      ${body}
      <p style="margin-top:24px;color:#5b665f">A PDF copy of this enquiry is attached.</p>
    </div>
  `;
}

export function getText({ title, sections }) {
  return [
    title,
    "",
    ...sections.flatMap((section) => [
      section.heading,
      ...section.rows.map(([label, value]) => `${label}: ${clean(value) || "Not entered"}`),
      "",
    ]),
    "A PDF copy of this enquiry is attached.",
  ].join("\n");
}

export async function sendEnquiryMail({ subject, replyTo, title, sections, filename }) {
  const transport = getTransport();
  const pdf = await getPdfBuffer({ title, sections });

  if (await sendWithResend({ subject, replyTo, title, sections, filename, pdf })) {
    return Response.json({ ok: true });
  }

  if (!transport) {
    return missingEmailConfigResponse();
  }

  await transport.sendMail({
    from: process.env.CONTACT_FROM_EMAIL || process.env.SMTP_USER,
    to: toEmail,
    replyTo,
    subject,
    text: getText({ title, sections }),
    html: getHtml({ title, sections }),
    attachments: [
      {
        filename,
        content: pdf,
        contentType: "application/pdf",
      },
    ],
  });

  return Response.json({ ok: true });
}
